# colors
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARK_GREEN = (0, 128, 0)
BACKGROUND_COLOR = WHITE

# window
WINDOW_POSITION_X = 100
WINDOW_POSITION_Y = 100

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

# WINDOW_PADDING = 15

WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

# image paths
LIFE_FULL_IMAGE_PATH = './images/life_full.png'
LIFE_EMPTY_IMAGE_PATH = './images/life_empty.png'

# fonts
monospace_14 = ['monospace', 14]
monospace_25 = ['monospace', 25]

# time
TIME_UNIT = 1

# difficulty
DIFFICULTY_SCALE = 100

# points
POINTS_TEXT_X = WINDOW_WIDTH - 100
POINTS_TEXT_Y = 20

# lives
LIFE_WIDTH = 10
LIFE_POSITION_Y = 0
LIVES_COUNT_INIT = 100

# input level
INPUT_LEVEL_LABEL_X = WINDOW_WIDTH // 2 // 1.25
INPUT_LEVEL_LABEL_Y = 150

INPUT_LEVEL_TEXT_X = WINDOW_WIDTH // 2
INPUT_LEVEL_TEXT_Y = WINDOW_HEIGHT // 2 - 30
